Algoritmo "Dentro ou fora do intervalo"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Dentro ou fora do intervalo
// Autor(a)    : Lucas Vilarindo
// Data atual  : 07/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor (de 1 a 9): ")
   Leia(num)

   Se (num < 1) OU (num > 9) entao
      Escreva("Número fora do intervalo permitido")
   Senao
      Escreva("Número dentro do intervalo permitido")
   FimSe

Fimalgoritmo