Algoritmo "Divisiveis por 4, até 200"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Divisiveis por 4, até 200
// Autor(a)    : Lucas Vilarindo
// Data atual  : 13/04/2024
Var
   count: inteiro

Inicio
   Repita
      count <- count + 1
      Se count % 4 = 0 entao
         Escreval("O número ", count, " é divisivel por 4")
      FimSe
   Até count > 200



Fimalgoritmo